# Generated by Django 3.1.7 on 2021-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_myuser_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Site Elemanı'),
        ),
    ]
