# Generated by Django 3.1.7 on 2021-04-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210408_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='register_time',
        ),
    ]
