# Generated by Django 3.2 on 2021-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_myuser_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='logouttime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
