# Generated by Django 3.2 on 2021-04-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_myuser_logouttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='logouttime',
        ),
    ]
