# Generated by Django 3.2 on 2021-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_myuser_logouttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='author',
            field=models.BooleanField(default=False, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='site_user',
            field=models.BooleanField(default=True, verbose_name='Site Üyesi'),
        ),
    ]
