# Generated by Django 3.2 on 2021-06-05 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_paymentphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, verbose_name='Telefon Numarası'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentPhone',
        ),
    ]
