# Generated by Django 3.2 on 2021-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210605_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='05555555555', max_length=11, verbose_name='Telefon Numarası'),
        ),
    ]
