# Generated by Django 3.2 on 2021-05-09 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeary',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Bakım Modu'),
            preserve_default=False,
        ),
    ]
