# Generated by Django 3.2 on 2021-04-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210427_1806'),
        ('carts', '0003_cart_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pincode',
        ),
        migrations.AddField(
            model_name='cart',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pincode'),
        ),
    ]
