# Generated by Django 3.2 on 2021-04-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210427_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pincode',
        ),
    ]
