# Generated by Django 3.2 on 2021-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210428_0837'),
        ('carts', '0006_cart_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pincode',
            field=models.ManyToManyField(blank=True, null=True, to='products.PinCode'),
        ),
    ]
