# Generated by Django 3.2 on 2021-04-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_pincode_pincode_pin_code'),
        ('carts', '0007_alter_cart_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pincode',
        ),
        migrations.AddField(
            model_name='cart',
            name='pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincode', to='products.pincode'),
        ),
    ]
