# Generated by Django 3.2 on 2021-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_pincode_pincode_pin_code'),
        ('carts', '0008_auto_20210428_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='cart',
            name='pin_code',
            field=models.ManyToManyField(blank=True, to='products.PinCode'),
        ),
    ]
