# Generated by Django 3.2 on 2021-04-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('create', 'Oluşturuldu'), ('paid', 'Tedarik Aşamasında'), ('deliver', 'Teslim Edildi'), ('cancel', 'İptal Edildi')], default='created', max_length=120)),
                ('order_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=100)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.cart')),
            ],
        ),
    ]
