# Generated by Django 3.2 on 2021-04-27 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_billing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Oluşturuldu'), ('paid', 'Tedarik Aşamasında'), ('deliver', 'Teslim Edildi'), ('cancel', 'İptal Edildi')], default='created', max_length=120),
        ),
    ]
