# Generated by Django 3.2 on 2021-04-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategori Adı')),
                ('desc', models.TextField(max_length=200, verbose_name='Aaçıklama')),
                ('active', models.BooleanField(default=True, verbose_name='Yayın')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(upload_to='', verbose_name='Slide')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('sale_price', models.FloatField(max_length=200, verbose_name='Piyasa Fiaytı')),
                ('discount_price', models.FloatField(max_length=200, verbose_name='Satış Fiyatı')),
                ('is_active', models.BooleanField(default=False, verbose_name='Yayında')),
                ('stock', models.IntegerField(max_length=200, verbose_name='Stok')),
                ('productimg', models.ImageField(upload_to='', verbose_name='Ürün resmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Kategori')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.product')),
            ],
        ),
    ]
