# Generated by Django 3.2 on 2021-04-10 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Kategori Resmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Küçük resim'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=500, unique=True, verbose_name='link'),
            preserve_default=False,
        ),
    ]
