# Generated by Django 3.2 on 2021-04-17 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_commerce_discountproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000, verbose_name='Video linki'),
            preserve_default=False,
        ),
    ]
