# Generated by Django 3.2 on 2021-04-20 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Meta Açıklaması'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Başlık'),
            preserve_default=False,
        ),
    ]
