# Generated by Django 3.2 on 2021-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincode',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='pincode',
            field=models.ManyToManyField(blank=True, null=True, to='products.PinCode'),
        ),
    ]
