# Generated by Django 3.2 on 2021-04-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210427_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pincode',
        ),
        migrations.AddField(
            model_name='pincode',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
