# Generated by Django 3.2 on 2021-04-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210428_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincode',
            old_name='pincode',
            new_name='pin_code',
        ),
    ]
