# Generated by Django 3.2 on 2021-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_pincode_pincode_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='cart_id',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='cart_id'),
        ),
    ]
