# Generated by Django 3.2 on 2021-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_pincode_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pin_code',
            field=models.CharField(default='Kodunuz Tedairk Aşamasındadır.', max_length=255, verbose_name='Pin Kodu'),
        ),
    ]
