# Generated by Django 3.2 on 2021-04-28 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_pincode_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='cart_id',
            field=models.IntegerField(default=0, max_length=255, verbose_name='cart_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pincode',
            name='pin_code',
            field=models.CharField(blank=True, default='Kodunuz Tedairk Aşamasındadır.', max_length=255, null=True, verbose_name='Pin Kodu'),
        ),
    ]
