# Generated by Django 3.2 on 2021-04-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_pincode_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='product',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
