# Generated by Django 3.2 on 2021-05-18 19:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_pincode_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.BooleanField(default=False, verbose_name='İndirimliler'),
        ),
        migrations.AddField(
            model_name='product',
            name='most_seller',
            field=models.BooleanField(default=False, verbose_name='En Çok Satanlar'),
        ),
        migrations.AddField(
            model_name='product',
            name='news',
            field=models.BooleanField(default=False, verbose_name='Yeni Ürünler'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Aaçıklama'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='product',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
    ]
