# Generated by Django 3.2 on 2021-05-09 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210506_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Aaçıklama'),
        ),
    ]
