# Generated by Django 3.2 on 2021-05-09 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Kısa Açıklama'),
            preserve_default=False,
        ),
    ]
