# Generated by Django 3.2 on 2021-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_category_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.BooleanField(default=False, verbose_name='İndirimliler'),
        ),
        migrations.AddField(
            model_name='product',
            name='most_seller',
            field=models.BooleanField(default=False, verbose_name='En Çok Satanlar'),
        ),
        migrations.AddField(
            model_name='product',
            name='news',
            field=models.BooleanField(default=False, verbose_name='Yeni Ürünler'),
        ),
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
