# Generated by Django 3.2 on 2021-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_pincode_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pin_code',
            field=models.CharField(default='Kodunuz Tedairk Aşamasındadır.', max_length=255, verbose_name='Pin Kodu'),
        ),
    ]
