# Generated by Django 3.2 on 2021-05-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210509_1826'),
        ('products', '0020_alter_pincode_pin_code'),
    ]

    operations = [
    ]
