# Generated by Django 3.2 on 2021-05-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_newprodcut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewProdcut',
            new_name='NewProduct',
        ),
    ]
