# Generated by Django 3.2 on 2021-05-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210509_1826'),
        ('products', '0022_rename_newprodcut_newproduct'),
    ]

    operations = [
    ]
